name: "Build"
on:
  push:
    branches:
      - master
jobs:
  test:
    name: "Prefix Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v4.0.1
        with:
          tag_prefix: ""
