name: "Build"
on:
  push:
    branches:
      - master
jobs:
  test:
    name: "Prefix Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            "ubuntu-18.04",
            "ubuntu-16.04",
            "ubuntu-20.04",
            "windows-2019",
            "windows-2016",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v4.0.1
        with:
          tag_prefix: ""
